### PR TITLE
Add Codenvy factory to test this add-on inside Codenvy

### PR DESCRIPTION
**Pull request by benoitf**
### Codenvy Workspace Developer

Hello,

this pull request introduce a new button named ___“Codenvy workspace developer”___ in the README of the project.

Contribute

This button provides a way for any user or developer to test, modify, update the project without installing anything on his local computer.

Each time a user clicks on the link, ___a new workspace___ is created.
* runtime is powered by a Docker container (can be customized with its own Dockerfile).
* source code of the repository is cloned and set as workspace sources.
* a set of commands is added in order to work with this project.
* a default command is automatically triggered so project is automatically run.

note: It does not require ___any changes___ on the source code.

### CODE REVIEW

**Comment by exo-swf** [comment]
Can one of the admins verify this patch?

**Comment by mgreau** [comment]
Thanks for the PR :)

In AsciiDoc, you need to add a link attribute so that the image is clickable:
`image:http://link-to-my-image.svg["Codenvy eXo Developer Workspace", link="http://beta.codenvy/xxxx"]`

**Comment by benoitf** [comment]
yes I saw that too late. It is now fixed

**Comment by mgreau** [comment]
LGTM

**Pull request merged**
